### ISSUE TITLE
in firefox browser Images don't read in comic reader 

### ISSUE THREAD

**Issue by legendaryepics** [afzafri/Web-Comic-Reader#3]
after loading the comic file in Firefox , when you click on an image it doesn't work in the reader's viewer but rather just opens in browser without comics' navigation bar.

**Comment by afzafri** [comment]
Hi thanks for reporting the issue. Looks like the problem is with the LightGallery plugin which seems to not supporting the Firefox. I will try to fix it. Thanks.

**Comment by afzafri** [comment]
Updated the LightGallery plugin to the latest version, and tested with the latest Firefox this issue is no longer available. The Comic Reader can now be used in Firefox browser.
