### ISSUE TITLE
how to load .cbr files which are already in the same folder

### ISSUE THREAD

**Issue by inglesuniversal** [afzafri/Web-Comic-Reader#4]
I'm trying to run this code but get an error...

ON THE INDEX.HTML

            <select name="fileup" id="fileup">
                <option value="">Select Comic Title</option>
                <option value="https://domain.com/comic_reader/lib/comic_001.cbr">Comic Title 01</option>
                <option value="https://domain.com/comic_reader/lib/comic_002.cbr">Comic Title 2</option>
                <option value="https://domain.com/comic_reader/lib/comic_003.cbr">Comic Title 3</option>
            </select>

ON JAVASCRIPT

ERROR I GET THIS ERROR

script.js:43 Uncaught TypeError: Cannot read property '0' of undefined
    at HTMLSelectElement.<anonymous> (script.js:43)
    at HTMLSelectElement.dispatch (jquery-3.2.0.min.js:3)
    at HTMLSelectElement.q.handle (jquery-3.2.0.min.js:3)

HOPE you can help me fix it...

**Comment by afzafri** [comment]
Hi, I'm not sure what are you trying to achieve here but as far as I know that's not how file upload works. You cannot select files from select box with the URL values in it. It might be still possible, but required some server side scripting (php) code adjustment. For now, the original codes is for file upload.
