### ISSUE TITLE
zoom problems

### ISSUE THREAD

**Issue by Mathis-Aubry** [afzafri/Web-Comic-Reader#5]
Hello, 

Your project is so nice but would have been perfect if there was more zoom functionalities : 
- Allow ctrl + scroll for zooming
- Save zoom preferences from one page to another
- Add more zoom possibilities (right now it's not very progressive)
- Maybe add a zoom bar to be able to choose more precisely and easily 

Thank you for reading 👍

**Comment by afzafri** [comment]
Hi @Taximin , thanks for the idea.
Unfortunately this project rely on another 3rd party package for the gallery viewer, called lightGallery: https://www.lightgalleryjs.com/

Seems like this package does not have functionality. Maybe when there are free time I can look into another type of package that offer similar functionality for the zoom.
